Revert "package_manager: call createrepo with --dbpath pointing inside WORKDIR"
This reverts commit 3b6f8baa7cc9b67a7d2d636e929bdc0f19f40b1d.

The commit broke all builds at the rootfs stage with an error similar to:

NOTE: recipe wrlinux-image-glibc-small-1.0-r1: task do_rootfs: Started
ERROR: Index creation command \
  '/.../bitbake_build/tmp/sysroots/x86_64-linux/usr/bin/createrepo \
  --dbpath    /.../bitbake_build/tmp/work/qemux86-wrs-linux/wrlinux-image-glibc-small/1.0-r1/rpmdb/all \
  --update -q /.../bitbake_build/tmp/deploy/rpm/all' failed with return code 1:
Options Error: option --dbpath not recognized.

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>