linux-libc-headers: add description in bbfile
Issue: LIN8-2443

If setting IMAGE_INSTALL += "linux-libc-headers", do_rootfs will cause
error.
  ERROR: linux-libc-headers not found in the base feeds

This is because that there is no linux-libc-headers.rpm generated.

(LOCAL REV: NOT UPSTREAM) -- Not Applicable (just an usage issue)

Signed-off-by: Jian Liu <jian.liu@windriver.com>